### ISSUE TITLE
System calls not executed

### ISSUE THREAD

**Issue by stineb** [stineb/rsofun#10]
When running the code in the RMarkdown vignettes, functions work properly but their `system()` calls to bash scripts are not executed. However, when I source() the respective R source files and then copy function calls into the console and run it from there, it works. No idea why...

**Comment by jmaspons** [comment]
Are these public functions? Only the exported functions are available outside the package. The non-exported functions can be accessed through rsofun:::nonExportedFunction. Consider to export the necessary functions for the vignettes if they are relevant enough.
