### ISSUE TITLE
Issue knitting vignette_rsofun, output_calib 

### ISSUE THREAD

**Issue by APriori1** [stineb/rsofun#15]
### The following error occurs when knitting vignette_rsofun (nb: in the 'sofun/trunk' folder I have shortcuts to 'output_nc' and 'output' folders only): 

label: unnamed-chunk-13 (with options) 
List of 3
 $ message: logi FALSE
 $ warning: logi FALSE
 $ include: logi FALSE

rm: /Users/../alphadata01/bstocker/sofun/trunk//output_calib/calibtargets_tmp_example.txt: No such file or directory
 ------------SOFUN : FR-Pue-------------

At line 371 of file sofun_simsuite.f90 (unit = 2)
Fortran runtime error: Cannot open file 'output_calib/calibtargets_tmp_example.txt': No such file or directory

Error termination. Backtrace:
#0  0x1082301ac
#1  0x108230e45
#2  0x1082315d9
#3  0x1083f69d8
#4  0x1083f6ccc
#5  0x108083480
#6  0x108083c38
Quitting from lines 435-441 (vignette_rsofun.Rmd) 
Error: '~/alphadata01/bstocker/sofun/trunk//output_calib/calibtargets_tmp_example.txt' does not exist.
In addition: Warning message:
In system(paste0("echo ", simsuite, " ", sprintf("%f %f %f %f",  :
  running command 'echo example 0.050000 -9999.000000 1.000000 0.000000 | ./runpmodel_simsuite' had status 2
Execution halted

**Comment by khufkens** [comment]
Currently we are rewriting the vignettes, best to consult the only documentation for now.
