### ISSUE TITLE
the question about SWC_F_MDS

### ISSUE THREAD

**Issue by kongdd** [stineb/rsofun#16]
Hi stineb, 

I found `SWC_F_MDS` in your script. Could you tell me where can I found the depth of very layer `SWC_F_MDS_#`? Any document?
Thanks for your help!

Cheers,
Dongdong

**Comment by khufkens** [comment]
Hi @kongdd look at any references to the `ingestr` package. This question is old so I assumed fixed. The package has changes signfiicantly since your question so changes might apply
