### ISSUE TITLE
Install package issue & solution

### ISSUE THREAD

**Issue by yunkepeng** [stineb/rsofun#17]
For some new user who install rsofun package first time, there might be a possible issue occured after running the code **devtools::install_github("stineb/rsofun")**

Error name is: Failed to install 'rsofun' from github. Installation of package xxx had non-zero exit status.

If this occured, please have a check whether **RTools** has been setup in advance, beacasue we need this to link R to fortran, so that the whole function from rsofun can sucessfully work.

An official guidence about how to setup RTools is available here: https://cran.r-project.org/bin/windows/Rtools/ 

Please follow this link step-by-step 
(1) Setup RTools
(2) run a simple code in R after installation: writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
(3) restart R and check the workplace of RTools: Sys.which("make")
(4) re-install rsofun package again. 

Best wishes
Yunke

**Comment by yunkepeng** [comment]
In order to prevent possible error, it is suggested to update R version to **4.0.0**, so that the version is consistent with Rtools40 (where also in 4.0.0 version).

**Comment by khufkens** [comment]
Closing as this should be fixed and not really package related (unit tests on windows work)
