### ISSUE TITLE
Fix package dependencies

### ISSUE THREAD

**Issue by jmaspons** [stineb/rsofun#2]
External dependencies are listed in the DESCRIPTION file. For now, all of them are suggestions. If there is any external dependency which is a must, it can be a requirement and we can specify that in order to be installed automatically when the user install rsofun.

TODO: decide if we want to import external packages or we want to use packageName::fun() to refer to external functions from other packages (it avoids collisions if different imported packages have functions with the same name). Once decided, adapt the code accordingly (no requires() nor library() inside functions and checks for suggested packages)

See https://github.com/stineb/rsofun/commit/8e3df1185a43bddaa046acf0b857b5f9d17b357c

**Comment by stineb** [comment]
In cases that have created conflicts with function names from other packages, I have used `packageName::fun() `. Let's go with your suggestion, adding all required packages to DESCRIPTION. I guess we'll have to delete the require() and library() statements then after merge from branch R-package, right?

**Comment by stineb** [comment]
Can we make some dependencies optional? Only the following are crucial:

'dplyr' 'lubridate' 'Metrics' 'ncdf4' 'optimr' 'purrr' 'readr' 'rlang' 'stringr' 'tidyr'

**Comment by jmaspons** [comment]
All dependencies can be imports. The optional packages can be in Suggest like nnet or caret. I will have a look
