### ISSUE TITLE
LM3-PPA crashes on p-model

### ISSUE THREAD

**Issue by khufkens** [stineb/rsofun#39]
Exit cleanly, either trapping the FORTRAN exit code on the C wrapper side, or return NULL / NA directly from the FORTRAN routine.

**Comment by khufkens** [comment]
duplicate

**Comment by wengensheng** [comment]
Let me know please if you put something new in there. I am thinking of
keeping at least one cohort to avoid the crash of LM3-PPA. However, if you
can solve the issue from the engineering aspect, that would be great!

**Comment by khufkens** [comment]
Taking this back to the original thread.

https://github.com/stineb/rsofun/issues/24
