### ISSUE TITLE
 instantaneous jmax25 response was not strictly correct 

### ISSUE THREAD

**Issue by yunkepeng** [stineb/rsofun#40]
I think you convert to jmax25, basing on modified Arrhenius kinetics from Kattge & Knorr (2007).

However, see Smith and Keenan 2020 GCB - table 1 - first line Kattge & Knorr (2007). K25 is not 1, but depended on temperature and vcmax25. If strictly follow their design, then k25 should be updated in our version. Now we assumed [jmax25  = jmax  / ftemp_inst_jmax](https://github.com/stineb/rsofun/blob/a10e11eabdd30b6e448cb6035b2de6ab79480429/src/photosynth_pmodel.mod.f90#L340), which means k25 still equals to 1.
![image](https://user-images.githubusercontent.com/62582250/135833796-8b5db9d4-edd8-44f5-993e-0faa2149b7f8.png)
![image](https://user-images.githubusercontent.com/62582250/135833892-82dcc449-ae66-4dbc-bcb2-c09ab6dea22d.png)

**Comment by stineb** [comment]
The dependency of Jmax on Vcmax is accounted for in the P-model here through assuming the coordination hypothesis.
In this sense, the formulation in Table 1 pasted in above should be regarded as an apparent empirical relationship (against which the P-model-predicted Vcmax25 and Jmax25 can be tested.
In other words, for what we're doing here, the scaling applied [here](https://github.com/stineb/rsofun/blob/a10e11eabdd30b6e448cb6035b2de6ab79480429/src/photosynth_pmodel.mod.f90#L340) should be correct.
