### ISSUE TITLE
Data download from permanent repo for rsofun

### ISSUE THREAD

**Issue by stineb** [stineb/rsofun#5]
There are some files being read by functions of rsofun. For example: `"~/data/FLUXNET-2015_Tier1/meta/fluxnet_site_info_mysub.csv"` being read by `eval_sofun` (see `eval_sofun.R`). Whenever such a read from file is unavoidable, we should put the respective files on a permanent repository (e.g., Zenodo) and add a `data(rsofun)` function to retrieve all the necessary files from there.

**Comment by jmaspons** [comment]
We can include the file in the package. csv files go to inst/extdata/. If you 
want that the users have access to the data as a variable when they load the 
package, save the data frame as an .RData file and put it in the data/ folder. The data can be available without data() call if we add `LazyData: true` in the DESCRIPTION file.

If the data is used only inside the functions we can put it in R/Sysdata.rda
