### ISSUE TITLE
Write to file: where to?

### ISSUE THREAD

**Issue by stineb** [stineb/rsofun#9]
Some functions create new files that are subsequently used in other functions. For example `calib_sofun()` writing calibrated parameters into a CSV file. I suggest in such cases we write files into a subdirectory `./results/`. However, this requires the definition of a respective variable variable `resultsdir <- "./results/"` loaded into the namespace? How can this be defined?

**Comment by jmaspons** [comment]
We can use ?tempfile(). If the file are not relevant for the user and used internally by the functions without user interaction. Otherwise, we can add a path as a parameter for the functions.

**Comment by jmaspons** [comment]
We can do something liki https://github.com/MatMatt/MODIS/blob/master/R/MODISoptions.R

**Comment by khufkens** [comment]
When dealing with small files (such as parameters) this should be `tempfile()`. CRAN doesn't allow writing to any other location, unless explicitly set by the user (for obvious reasons).
